
version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=securepassword
      - N8N_HOST=n8n.local
      - N8N_PORT=5678
      - TZ=Europe/Amsterdam
    volumes:
      - ./n8n_data:/home/node/.n8n
      - ./files:/home/node/files
volumes:
  n8n_data:
